version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    env_file:
      - db.env

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db

  client:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - '80:80'

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - mongo.env

